### ISSUE TITLE
check geocoder results marker and bounds update

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/otl-neighborhood-change#8]
@ilyankou - I have installed esri leaflet geocoder but need your help
please check lines 131-152
https://github.com/OnTheLine/otl-neighborhood-change/blob/master/script.js#L131

- [x] display geocoder results as markers in map2 (e.g. "300 Summit St, Hartford CT")
- [x] if possible, update geocoder bounds to work with esri geocoder

**Comment by ilyankou** [comment]
Jack,

I pushed the changes to master. I think by your first item you mean displaying a popup with address text along with the marker, which I did in [lines 146-150](https://github.com/OnTheLine/otl-neighborhood-change/blob/master/script.js#L146-L150).

As for the bounding box, Esri geocoder comes with two relevant parameters: `useMapBounds` (true/false) and `searchBounds` (which is a custom bounding box). [See documentation](http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#options).

I deleted our custom Nominatim code that calculates the bounding box and replaced it with Esri's `useMapBounds: true` (which is its default behavior, but nice to spell anyway). In other words, I replicated the old Nominatim behavior: zooming in to downtown Hartford, you won't find 300 Summit St because it's outside of the current viewing box.

Alternatively, you can uncomment the [line](https://github.com/OnTheLine/otl-neighborhood-change/blob/master/script.js#L135) under it to enable search in all of CT (with some NY, MA, and RI) disregarding current zoom & view.

**Comment by ilyankou** [comment]
I have noticed that at times when the location is just outside of the bounds of the current view, it still appears in the list of suggestions, but once I click – the map doesn't fly anywhere and the results marker is not created. Let me know if you experience this.

**Comment by JackDougherty** [comment]
Thanks for updates, but now the geocoder bounds are too narrow. In the default opening view, when I try to type an area that is not currently shown in the map view (such as "Simsbury CT"), this result does not appear in the results. But if I zoom the map out, the "Simsbury" result appears.

Perhaps the original map worked this way, but it's not my intended design. The geocoding bounds should be limited to approximate CT boundaries. Any user should be able to search any CT address at any time, but not beyond because the 1934 map does not extend beyond CT boundaries. Let me know if you need more info from me.

**Comment by ilyankou** [comment]
Jack—the geocoder should now search within CT, not current view. Let me know.

**Comment by JackDougherty** [comment]
Perfect on the geocoder! 

One more small request to add to my bill: please adjust the CSS so that this version fills the height of the page
https://ontheline.github.io/otl-neighborhood-change/index-caption.html

**Comment by ilyankou** [comment]
Jack–

Current code hides "Powered by Esri" on map2, I fixed that (not yet committed).

It will always be a bit tricky combining the iframe and the text, because based on the screen width text might become fairly long and thus require more screen height.

What do you think of this solution:
1. 85% of height is always the map
1. 15% of height is always text underneath
1. On larger displays, text is shown in 3 columns (much better for readability)
1. On smaller displays, text is one column
1. Text box has a scroll, not the body

![Screenshot 2020-03-10 at 15 34 05](https://user-images.githubusercontent.com/10443203/76330203-7947c180-62e5-11ea-88da-740f9d7535c1.png)

![Screenshot 2020-03-10 at 15 33 39](https://user-images.githubusercontent.com/10443203/76329882-0a6a6880-62e5-11ea-8013-bd0ec1d6b130.png)

**Comment by JackDougherty** [comment]
I like all of your suggestions, but please keep the caption as one column in all displays. I understand what you're saying about readability, but the need for uniformity across maps is greater.

**Comment by ilyankou** [comment]
Should be as requested now.
